# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

dist: trusty
sudo: false
language: cpp

install:
  # /usr/bin/gcc is 4.6 always, but gcc-X.Y is available.
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  # /usr/bin/clang is 3.4, lets override with modern one.
  - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports # cmake 3.2.3
    packages:
      - gcc5
      - g++-5
      - valgrind
      - cmake
      - cmake-data

matrix:
  include:
    - os: linux
      compiler: g++
      env: CC="gcc-5" CXX="g++-5" BUILD_TYPE=Debug CXX_FLAGS=-std=c++14

# compiler:
#   - g++
#   - clang

script:
  - ./travis.sh

notifications:
  email: false
  slack: veloxcapital:YLypZanCflsuwci44VOggtGS
